version: '3.8'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - "3000:80"
    restart: unless-stopped
    networks:
      - react-network

networks:
  react-network:
    driver: bridge