version: '3.8'
services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: angular-app
    ports:
      - "4200:80"
    restart: unless-stopped
    networks:
      - angular-network

networks:
  angular-network:
    driver: bridge