version: '3.8'
services:
  solid-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: solid-app
    ports:
      - "3000:80"
    restart: unless-stopped
    networks:
      - solid-network

networks:
  solid-network:
    driver: bridge